local hl = require("hyprland")

hl.config({
    autogenerated = false,
})

----------------
-- MONITORS
----------------

hl.monitor({
    name = "",
    mode = "1920x1080@60",
    position = "0x0",
    scale = 1,
})

-- Old commented monitors preserved:
-- hl.monitor({ name = "DP-1", mode = "1920x1080@60", position = "auto", scale = 1 })
-- hl.monitor({ name = "DP-2", mode = "3440x1440@144", position = "auto", scale = 1 })
-- hl.monitor({ name = "DP-3", mode = "1920x1080@60", position = "auto", scale = 1 })

----------------
-- VARIABLES
----------------

local terminal = "kitty"
local fileManager = "thunar"
local menu = "rofi -show drun -config /home/alikornsause/nixosConfig/rofi/rofidmenu.rasi"
local browser = "librewolf"

----------------
-- AUTOSTART
----------------

hl.exec_once("waybar")
hl.exec_once("swww-daemon")
hl.exec_once("swww img /home/alikornsause/image.jpg")
hl.exec("amixer set Master 100%-")
hl.exec_once("/nix/store/1r81gjfrmc40yln23f0zw92swy8gcv7x-polkit-gnome-0.105/libexec/polkit-gnome-authentication-agent-1")

----------------
-- ENVIRONMENT
----------------

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

----------------
-- GENERAL
----------------

hl.general({
    gaps_in = 0,
    gaps_out = 0,
    border_size = 5,

    ["col.active_border"] = "rgba(99999999) rgba(000000ff) 90deg",
    ["col.inactive_border"] = "rgba(999999ff)",

    resize_on_border = true,
    allow_tearing = false,
    layout = "dwindle",
})

----------------
-- DECORATION
----------------

hl.decoration({
    rounding = 0,

    active_opacity = 1.0,
    inactive_opacity = 0.85,

    dim_inactive = true,
    dim_strength = 0.2,

    shadow = {
        enabled = false,
        range = 4,
        render_power = 3,
        color = "rgba(1a1a1aee)",
    },
})

----------------
-- ANIMATIONS
----------------

hl.animations({
    enabled = false,

    bezier = {
        "easeOutQuint,0.23,1,0.32,1",
        "easeInOutCubic,0.65,0.05,0.36,1",
        "linear,0,0,1,1",
        "almostLinear,0.5,0.5,0.75,1.0",
        "quick,0.15,0,0.1,1",
        "infade,0,0.5,0.14,0.53",
    },

    animation = {
        "global, 1, 10, default",
        "border, 1, 5.39, easeOutQuint",
        "windows, 1, 4.79, easeOutQuint",
        "windowsIn, 1, 4.1, easeOutQuint, slidefade 87%",
        "windowsOut, 1, 1.49, linear, slidefade 87%",
        "fadeIn, 1, 1.73, almostLinear",
        "fadeOut, 1, 1.46, almostLinear",
        "fade, 1, 3.03, quick",
        "layers, 1, 3.81, easeOutQuint",
        "layersIn, 1, 4, easeOutQuint, fade",
        "layersOut, 1, 1.5, linear, fade",
        "fadeLayersIn, 1, 1.79, almostLinear",
        "fadeLayersOut, 1, 1.39, almostLinear",
        "workspaces, 1, 1.94, almostLinear, fade",
        "workspacesIn, 1, 1.21, almostLinear, fade",
        "workspacesOut, 1, 1.94, almostLinear, fade",
    },
})

----------------
-- LAYOUTS
----------------

hl.dwindle({
    preserve_split = true,
})

hl.master({
    new_status = "master",
})

----------------
-- MISC
----------------

hl.misc({
    force_default_wallpaper = 0,
    disable_hyprland_logo = true,
})

----------------
-- INPUT
----------------

hl.input({
    kb_layout = "pl",

    scroll_method = "edge",
    follow_mouse = 1,

    sensitivity = 0.3,

    touchpad = {
        natural_scroll = true,
    },
})

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})

----------------
-- MODIFIERS
----------------

local mainMod = "SUPER"

----------------
-- KEYBINDS
----------------

local bind = hl.bind
local binde = hl.binde
local bindm = hl.bindm
local bindl = hl.bindl

bind(mainMod, "F1", "exec", "~/dev/fanControl/fanctl")
bind(mainMod, "F2", "exec", "python3 ~/.config/waybar/scripts/network-eth-manager.py")
bind(mainMod, "F3", "exec", "nmgui")
bind(mainMod, "F4", "exec", "GTK_THEME=Adwaita:dark modem-manager-gui")
bind(mainMod, "F5", "exec", "blueman-manager")
bind(mainMod, "F6", "exec", "pavucontrol")

bind(mainMod, "Return", "exec", terminal)
bind(mainMod, "B", "exec", browser)
bind(mainMod .. " SHIFT", "B", "exec", browser .. " --private-window")
bind(mainMod, "E", "exec", fileManager)

bind(mainMod, "W", "killactive")
bind(mainMod, "V", "togglefloating")
bind(mainMod, "J", "layoutmsg", "togglesplit")
bind(mainMod, "F", "fullscreen")
bind(mainMod, "M", "exec", menu)

bind("", "Print", "exec", "flameshot gui --clipboard --path /home/alikornsause/Pictures/Screenshots")
bind(mainMod .. " SHIFT", "S", "exec", "flameshot gui --clipboard --path /home/alikornsause/Pictures/Screenshots")

bind(mainMod, "T", "exec", "pkill waybar || waybar")
bind("SUPER", "L", "exec", "hyprlock")

-- Resize
binde("SUPER ALT", "left", "resizeactive", "-20 0")
binde("SUPER ALT", "right", "resizeactive", "20 0")
binde("SUPER ALT", "up", "resizeactive", "0 -20")
binde("SUPER ALT", "down", "resizeactive", "0 20")

-- Move windows
bind("SUPER SHIFT", "left", "movewindow", "l")
bind("SUPER SHIFT", "right", "movewindow", "r")
bind("SUPER SHIFT", "up", "movewindow", "u")
bind("SUPER SHIFT", "down", "movewindow", "d")

-- Focus
bind(mainMod, "left", "movefocus", "l")
bind(mainMod, "right", "movefocus", "r")
bind(mainMod, "up", "movefocus", "u")
bind(mainMod, "down", "movefocus", "d")

-- Workspaces
for i = 1, 9 do
    bind(mainMod, tostring(i), "workspace", tostring(i))
    bind(mainMod .. " SHIFT", tostring(i), "movetoworkspace", tostring(i))
end

bind(mainMod, "0", "workspace", "10")
bind(mainMod, "minus", "workspace", "11")
bind(mainMod, "equal", "workspace", "12")
bind(mainMod, "backspace", "workspace", "13")
bind(mainMod, "grave", "workspace", "100")

bind(mainMod .. " SHIFT", "0", "movetoworkspace", "10")
bind(mainMod .. " SHIFT", "minus", "movetoworkspace", "11")
bind(mainMod .. " SHIFT", "equal", "movetoworkspace", "12")
bind(mainMod .. " SHIFT", "backspace", "movetoworkspace", "13")
bind(mainMod .. " SHIFT", "grave", "movetoworkspace", "100")

bind(mainMod, "SPACE", "togglefloating")

bind(mainMod, "mouse_down", "workspace", "e+1")
bind(mainMod, "mouse_up", "workspace", "e-1")

bindm(mainMod, "mouse:272", "movewindow")
bindm(mainMod, "mouse:273", "resizewindow")

-- Volume / brightness
binde("", "XF86AudioRaiseVolume", "exec", "pamixer -i 2")
binde("", "XF86AudioLowerVolume", "exec", "pamixer -d 2")
bind("", "XF86AudioMute", "exec", "pamixer -t")

bindl(
    "",
    "XF86AudioMicMute",
    "exec",
    "/home/alikornsause/nixosConfig/waybar/scripts/mic-toggle.sh toggle"
)

bind("", "XF86MonBrightnessUp", "exec", "brightnessctl set +5%")
bind("", "XF86MonBrightnessDown", "exec", "brightnessctl set 5%-")

----------------
-- WINDOW RULES
----------------

hl.windowrule({
    match = {
        class = "com.network.manager",
    },

    actions = {
        "float",
    },
})

hl.windowrule({
    match = {
        class = "modem-manager-gui",
    },

    actions = {
        "float",
    },
})

hl.windowrule({
    match = {
        class = "blueman-manager",
    },

    actions = {
        "float",
    },
})

hl.windowrule({
    match = {
        class = "org.pulseaudio.pavucontrol",
    },

    actions = {
        "float",
    },
})